name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache
      
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    permissions:
      id-token: write # Required for OIDC trusted publishing

    steps:
      - uses: actions/checkout@v4

      # Install uv and Python
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      # Cache uv's dependency cache to speed up installs
      - name: Cache uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build the project
        run: uv build

      # Trusted Publishing to TestPyPI
      - name: Publish to TestPyPI
        if: github.ref == 'refs/heads/main'
        run: uv publish --index TestPyPI

      - name: Minimize uv cache
        run: uv cache prune --ci
